services:
  - type: web
    name: docqa-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: API_KEY
        value: hf_Your_Valid_HuggingFace_Token
    plan: free
    rootDir: backend
